_book01_stages = [
	# [stage-name, start-node, end-node, [badges]],
	['',		'000', '000', []],
	['stage1',	'001', '018', ['m1', 'm2', 'p1', 's1']],
	['stage2',	'020', '049', ['c1', 'm3']],
	['stage3',	'050', '089', ['c2', 'p2', 'x1', 'x2']],
	['stage4',	'090', '098', ['t1']],
	['stage5',	'099', '299', ['i1', 'i2', 'i3', 'p3', 's2', 's3', 'v1', 'v2', 'z1']],
	['stage6',	'300', '345', ['t2', 't3']],
	['stage7',	'350', '395', ['f1', 'i4', 'l1']],
	['stage8',	'400', '445', ['i5', 'l2', 'x3']],
	['stage9',	'450', '495', ['f2', 'l3', 'p4', 'x4']],
	['',		'500', '500', []],	# Final
]

_book01_badges = {
	'c1': 'Collision I - Basic',
	'c2': 'Collision II - Advanced',
	'f1': 'Fluff I - Ouch',
	'f2': 'Fluff II - Glasses',
	'i1': 'Treasure I - Key',
	'i2': 'Treasure II - Finish',
	'i3': 'Treasure III - Potion',
	'i4': 'Treasure IV - Coin',
	'i5': 'Treasure V - Better Potion',
	'l1': 'Level I',
	'l2': 'Level II',
	'l3': 'Level III',
	'm1': 'Movement I - Horizontal',
	'm2': 'Movement II - Friction',
	'm3': 'Movement III - Gravity',
	'p1': 'Platform I - Base',
	'p2': 'Platform II - Four Sided',
	'p3': 'Platform III - Pattern',
	'p4': 'Platform IV - Moving',
	's1': 'Sprite I - Origin',
	's2': 'Sprite II - Image',
	's3': 'Sprite III - Direction',
	't1': 'Transition I - Levels',
	't2': 'Transition II - Title',
	't3': 'Transition III - Timer',
	'v1': 'Vitality I - Health',
	'v2': 'Vitality II - Reincarnation',
	'x1': 'Monster I - Stationary',
	'x2': 'Monster II - Roaming',
	'x3': 'Monster III - Animate',
	'x4': 'Monster IV - Projectile',
	'z1': 'Challenge I',
}

_book01_optional_badges = ['z1']

_book01_images = {
	'images/player/normal.png': '20x24',
	'images/player/happy.png': '20x24',
	'images/player/ooo.png': '20x24',
	'images/player/sad.png': '30x17',
	'images/player/glasses.png': '20x24',
	'images/player/icon.png': '14x17',
	'images/monsters/vlad.png': '20x24',
	'images/monsters/henrietta.png': '30x30',
	'images/monsters/rufus.png': '28x26',
	'images/monsters/prescott.png': '26x28',
	'images/monsters/doppleganger.png': '20x24',
	'images/monsters/falco1.png': '40x24',
	'images/monsters/falco2.png': '40x24',
	'images/monsters/octoboss1.png': '38x24',
	'images/monsters/octoboss2.png': '38x24',
	'images/monsters/octoboss3.png': '38x24',
	'images/monsters/eyes0.png': '20x20',
	'images/monsters/eyes1.png': '20x20',
	'images/monsters/eyes2.png': '20x20',
	'images/monsters/ball-left.png': '10x5',
	'images/monsters/ball-right.png': '10x5',
	'images/items/key.png': '18x20',
	'images/items/gem.png': '21x27',
	'images/items/potion.png': '16x23',
	'images/items/coin.png': '20x20',
	'images/items/potion-1.png': '16x23',
	'images/items/potion-2.png': '16x23',
	'images/items/potion-3.png': '16x23',
	'images/items/potion-4.png': '16x23',
	'images/items/potion-5.png': '16x23',
	'images/items/potion-6.png': '16x23',
	'images/items/potion-7.png': '16x23',
	'images/items/potion-8.png': '16x23',
	'images/items/potion-9.png': '16x23',
	'images/items/potion-10.png': '16x23',
	'images/items/potion-11.png': '16x23',
	'images/items/potion-12.png': '16x23',
	'images/items/potion-13.png': '16x23',
	'images/items/potion-14.png': '16x23',
	'images/items/potion-15.png': '16x23',
	'images/backgrounds/block.png': '20x20',
	'images/backgrounds/block2.png': '20x20',
	'images/backgrounds/block-red.png': '20x20',
	'images/backgrounds/candycane.png': '20x20',
	'images/backgrounds/dirt.png': '40x20',
	'images/backgrounds/brick.png': '9x8',
	'images/backgrounds/post.png': '10x10',
	'images/backgrounds/wheel.png': '10x10',
	'images/backgrounds/gate-closed.png': '30x40',
	'images/backgrounds/gate-open.png': '30x40',
}

_book01_functions = [
	'setup',

	'handle_load',
	'handle_keydown',
	'handle_keyup',

	'init',
	'init_game',

	'init_player',
	'init_player_sprite',
	'update_player_sprite',

	'init_level_defaults',
	'init_level0_title',
	'init_level1',
	'init_level2',
	'init_level3',

	'add_platforms',
	'add_default_platforms',
	'add_moving_platforms',
	'create_platform',

	'add_monsters',
	'add_projectile_monsters',
	'add_eyeball_monsters',
	'create_monster',

	'add_items',
	'add_potion_item',
	'create_item',

	'create_goal',

	'start_level',
	'complete_level',
	'lose_life',
	'adjust_health',

	'set_transform_xy',
	'set_transform',
	'reset_transform',

	'draw',
	'erase',
	'draw_platforms',
	'draw_monsters',
	'draw_items',
	'draw_goal',
	'draw_player',
	'draw_status',

	'draw_title_screen',
	'draw_transition_screen',

	'update_platforms',
	'update_monsters',
	'update_items',
	'update_player',

	'check_input',

	'check_collisions',
	'check_platform_collisions',
	'check_monster_collisions',
	'check_item_collisions',
	'check_goal_collisions',

	'collide',

	'update_world',
]

_book01_info = [
	_book01_stages,
	_book01_badges,
	_book01_optional_badges,
	_book01_images,
	_book01_functions,
]
